Traceback (most recent call last):
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/xaru/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/xaru/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import spacy
nlp = spacy.load("en_core_web_sm", exclude=["ner", "senter"])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-1-aa4c61613960>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mspacy[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mnlp[0m [0;34m=[0m [0mspacy[0m[0;34m.[0m[0mload[0m[0;34m([0m[0;34m"en_core_web_sm"[0m[0;34m,[0m [0mexclude[0m[0;34m=[0m[0;34m[[0m[0;34m"ner"[0m[0;34m,[0m [0;34m"senter"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m
[0m
[0;32m~/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/spacy/__init__.py[0m in [0;36mload[0;34m(name, vocab, disable, exclude, config)[0m
[1;32m     50[0m     """
[1;32m     51[0m     return util.load_model(
[0;32m---> 52[0;31m         [0mname[0m[0;34m,[0m [0mvocab[0m[0;34m=[0m[0mvocab[0m[0;34m,[0m [0mdisable[0m[0;34m=[0m[0mdisable[0m[0;34m,[0m [0mexclude[0m[0;34m=[0m[0mexclude[0m[0;34m,[0m [0mconfig[0m[0;34m=[0m[0mconfig[0m[0;34m[0m[0m
[0m[1;32m     53[0m     )
[1;32m     54[0m [0;34m[0m[0m

[0;32m~/.local/share/virtualenvs/przetwarzanie-danych-i-odkrywanie-wiedzy-jTddvZuD/lib/python3.6/site-packages/spacy/util.py[0m in [0;36mload_model[0;34m(name, vocab, disable, exclude, config)[0m
[1;32m    425[0m     [0;32mif[0m [0mname[0m [0;32min[0m [0mOLD_MODEL_SHORTCUTS[0m[0;34m:[0m[0;34m[0m[0m
[1;32m    426[0m         [0;32mraise[0m [0mIOError[0m[0;34m([0m[0mErrors[0m[0;34m.[0m[0mE941[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mname[0m[0;34m=[0m[0mname[0m[0;34m,[0m [0mfull[0m[0;34m=[0m[0mOLD_MODEL_SHORTCUTS[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m)[0m[0;34m)[0m  [0;31m# type: ignore[index][0m[0;34m[0m[0m
[0;32m--> 427[0;31m     [0;32mraise[0m [0mIOError[0m[0;34m([0m[0mErrors[0m[0;34m.[0m[0mE050[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mname[0m[0;34m=[0m[0mname[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    428[0m [0;34m[0m[0m
[1;32m    429[0m [0;34m[0m[0m

[0;31mOSError[0m: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

